services:
  db:
    image: postgis/postgis:17-3.5
    container_name: echo_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: echo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      # Map the sql directory to initialize schema and seed data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    restart: unless-stopped

volumes:
  db_data: