// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ReportStatus string

const (
	ReportStatusLOGGED         ReportStatus = "LOGGED"
	ReportStatusACTIONREQUIRED ReportStatus = "ACTION_REQUIRED"
	ReportStatusDISPATCHED     ReportStatus = "DISPATCHED"
	ReportStatusRESOLVED       ReportStatus = "RESOLVED"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus `json:"report_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type UserRole string

const (
	UserRoleSTUDENT          UserRole = "STUDENT"
	UserRoleSANITATIONWORKER UserRole = "SANITATION_WORKER"
	UserRoleELECTRICIAN      UserRole = "ELECTRICIAN"
	UserRoleSECURITY         UserRole = "SECURITY"
	UserRoleADMIN            UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type CampusResource struct {
	ID           string             `json:"id"`
	Title        string             `json:"title"`
	ResourceType string             `json:"resource_type"`
	TargetUrl    string             `json:"target_url"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Report struct {
	ID           pgtype.UUID        `json:"id"`
	ReporterID   pgtype.UUID        `json:"reporter_id"`
	Status       ReportStatus       `json:"status"`
	LocationGeom interface{}        `json:"location_geom"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	UniversityID string             `json:"university_id"`
	PinHash      pgtype.Text        `json:"pin_hash"`
	AuthProvider string             `json:"auth_provider"`
	ProviderID   pgtype.Text        `json:"provider_id"`
	Role         UserRole           `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
