// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, location_geom, image_url, metadata)
VALUES ($1, ST_SetSRID(ST_MakePoint($2, $3), 4326), $4, $5)
RETURNING id, reporter_id, status, image_url, metadata, created_at, ST_X(location_geom::geometry) as longitude, ST_Y(location_geom::geometry) as latitude
`

type CreateReportParams struct {
	ReporterID    pgtype.UUID `json:"reporter_id"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	ImageUrl      pgtype.Text `json:"image_url"`
	Metadata      []byte      `json:"metadata"`
}

type CreateReportRow struct {
	ID         pgtype.UUID        `json:"id"`
	ReporterID pgtype.UUID        `json:"reporter_id"`
	Status     ReportStatus       `json:"status"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Longitude  interface{}        `json:"longitude"`
	Latitude   interface{}        `json:"latitude"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (CreateReportRow, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.ImageUrl,
		arg.Metadata,
	)
	var i CreateReportRow
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.Status,
		&i.ImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, reporter_id, status, image_url, metadata, created_at, ST_X(location_geom::geometry) as longitude, ST_Y(location_geom::geometry) as latitude FROM reports WHERE id = $1
`

type GetReportByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	ReporterID pgtype.UUID        `json:"reporter_id"`
	Status     ReportStatus       `json:"status"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Longitude  interface{}        `json:"longitude"`
	Latitude   interface{}        `json:"latitude"`
}

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (GetReportByIDRow, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i GetReportByIDRow
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.Status,
		&i.ImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const getReportsWithinRadius = `-- name: GetReportsWithinRadius :many
SELECT r.id, r.reporter_id, u.university_id as reporter_university_id, r.status, r.image_url, r.metadata, r.created_at, ST_X(r.location_geom::geometry) as longitude, ST_Y(r.location_geom::geometry) as latitude 
FROM reports r
JOIN users u ON r.reporter_id = u.id
WHERE ST_DWithin(r.location_geom::geography, ST_SetSRID(ST_MakePoint($1, $2), 4326)::geography, $3)
`

type GetReportsWithinRadiusParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	StDwithin     interface{} `json:"st_dwithin"`
}

type GetReportsWithinRadiusRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ReporterID           pgtype.UUID        `json:"reporter_id"`
	ReporterUniversityID string             `json:"reporter_university_id"`
	Status               ReportStatus       `json:"status"`
	ImageUrl             pgtype.Text        `json:"image_url"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Longitude            interface{}        `json:"longitude"`
	Latitude             interface{}        `json:"latitude"`
}

func (q *Queries) GetReportsWithinRadius(ctx context.Context, arg GetReportsWithinRadiusParams) ([]GetReportsWithinRadiusRow, error) {
	rows, err := q.db.Query(ctx, getReportsWithinRadius, arg.StMakepoint, arg.StMakepoint_2, arg.StDwithin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsWithinRadiusRow
	for rows.Next() {
		var i GetReportsWithinRadiusRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReporterUniversityID,
			&i.Status,
			&i.ImageUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, university_id, pin_hash, auth_provider, provider_id, role, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.PinHash,
		&i.AuthProvider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUniversityID = `-- name: GetUserByUniversityID :one
SELECT id, university_id, pin_hash, auth_provider, provider_id, role, created_at FROM users WHERE university_id = $1
`

func (q *Queries) GetUserByUniversityID(ctx context.Context, universityID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUniversityID, universityID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.PinHash,
		&i.AuthProvider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateReportMetadata = `-- name: UpdateReportMetadata :exec
UPDATE reports SET metadata = $2 WHERE id = $1
`

type UpdateReportMetadataParams struct {
	ID       pgtype.UUID `json:"id"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) UpdateReportMetadata(ctx context.Context, arg UpdateReportMetadataParams) error {
	_, err := q.db.Exec(ctx, updateReportMetadata, arg.ID, arg.Metadata)
	return err
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE reports SET status = $2 WHERE id = $1
`

type UpdateReportStatusParams struct {
	ID     pgtype.UUID  `json:"id"`
	Status ReportStatus `json:"status"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.Exec(ctx, updateReportStatus, arg.ID, arg.Status)
	return err
}
