// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateReport(ctx context.Context, arg CreateReportParams) (CreateReportRow, error)
	DeleteReport(ctx context.Context, id pgtype.UUID) error
	GetReportByID(ctx context.Context, id pgtype.UUID) (GetReportByIDRow, error)
	GetReportsWithinRadius(ctx context.Context, arg GetReportsWithinRadiusParams) ([]GetReportsWithinRadiusRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUniversityID(ctx context.Context, universityID string) (User, error)
	UpdateReportMetadata(ctx context.Context, arg UpdateReportMetadataParams) error
	UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error
}

var _ Querier = (*Queries)(nil)
