// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkDistance = `-- name: CheckDistance :one
SELECT ST_Distance(
    ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography,
    location_geom::geography
)::float8 AS distance
FROM reports
WHERE id = $3
`

type CheckDistanceParams struct {
	Column1 float64     `json:"column_1"`
	Column2 float64     `json:"column_2"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) CheckDistance(ctx context.Context, arg CheckDistanceParams) (float64, error) {
	row := q.db.QueryRow(ctx, checkDistance, arg.Column1, arg.Column2, arg.ID)
	var distance float64
	err := row.Scan(&distance)
	return distance, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, location_geom, image_url, metadata)
VALUES ($1, ST_SetSRID(ST_MakePoint($2, $3), 4326), $4, $5)
RETURNING id, reporter_id, status, image_url, metadata, created_at, ST_X(location_geom::geometry) as longitude, ST_Y(location_geom::geometry) as latitude
`

type CreateReportParams struct {
	ReporterID    pgtype.UUID `json:"reporter_id"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	ImageUrl      pgtype.Text `json:"image_url"`
	Metadata      string      `json:"metadata"`
}

type CreateReportRow struct {
	ID         pgtype.UUID        `json:"id"`
	ReporterID pgtype.UUID        `json:"reporter_id"`
	Status     ReportStatus       `json:"status"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	Metadata   string             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Longitude  interface{}        `json:"longitude"`
	Latitude   interface{}        `json:"latitude"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (CreateReportRow, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.ImageUrl,
		arg.Metadata,
	)
	var i CreateReportRow
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.Status,
		&i.ImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (university_id, pin_hash, role, auth_provider)
VALUES ($1, $2, $3, $4)
RETURNING id, university_id, pin_hash, auth_provider, provider_id, role, created_at
`

type CreateUserParams struct {
	UniversityID string      `json:"university_id"`
	PinHash      pgtype.Text `json:"pin_hash"`
	Role         UserRole    `json:"role"`
	AuthProvider string      `json:"auth_provider"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UniversityID,
		arg.PinHash,
		arg.Role,
		arg.AuthProvider,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.PinHash,
		&i.AuthProvider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllReports = `-- name: GetAllReports :many
SELECT r.id, r.reporter_id, u.university_id as reporter_university_id, r.status, r.image_url, r.metadata, r.created_at, ST_X(r.location_geom::geometry) as longitude, ST_Y(r.location_geom::geometry) as latitude
FROM reports r
JOIN users u ON r.reporter_id = u.id
ORDER BY r.created_at DESC
`

type GetAllReportsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ReporterID           pgtype.UUID        `json:"reporter_id"`
	ReporterUniversityID string             `json:"reporter_university_id"`
	Status               ReportStatus       `json:"status"`
	ImageUrl             pgtype.Text        `json:"image_url"`
	Metadata             string             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Longitude            interface{}        `json:"longitude"`
	Latitude             interface{}        `json:"latitude"`
}

func (q *Queries) GetAllReports(ctx context.Context) ([]GetAllReportsRow, error) {
	rows, err := q.db.Query(ctx, getAllReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllReportsRow
	for rows.Next() {
		var i GetAllReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReporterUniversityID,
			&i.Status,
			&i.ImageUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, university_id, pin_hash, auth_provider, provider_id, role, created_at FROM users ORDER BY created_at DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UniversityID,
			&i.PinHash,
			&i.AuthProvider,
			&i.ProviderID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, reporter_id, status, image_url, metadata, created_at, ST_X(location_geom::geometry) as longitude, ST_Y(location_geom::geometry) as latitude FROM reports WHERE id = $1
`

type GetReportByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	ReporterID pgtype.UUID        `json:"reporter_id"`
	Status     ReportStatus       `json:"status"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	Metadata   string             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Longitude  interface{}        `json:"longitude"`
	Latitude   interface{}        `json:"latitude"`
}

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (GetReportByIDRow, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i GetReportByIDRow
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.Status,
		&i.ImageUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const getReportsByDepartmentAndStatus = `-- name: GetReportsByDepartmentAndStatus :many
SELECT r.id, r.reporter_id, u.university_id as reporter_university_id, r.status, r.image_url, r.metadata, r.created_at, ST_X(r.location_geom::geometry) as longitude, ST_Y(r.location_geom::geometry) as latitude
FROM reports r
JOIN users u ON r.reporter_id = u.id
WHERE (r.metadata->>'department') = $1::text AND r.status = $2
ORDER BY r.created_at DESC
`

type GetReportsByDepartmentAndStatusParams struct {
	Column1 string       `json:"column_1"`
	Status  ReportStatus `json:"status"`
}

type GetReportsByDepartmentAndStatusRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ReporterID           pgtype.UUID        `json:"reporter_id"`
	ReporterUniversityID string             `json:"reporter_university_id"`
	Status               ReportStatus       `json:"status"`
	ImageUrl             pgtype.Text        `json:"image_url"`
	Metadata             string             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Longitude            interface{}        `json:"longitude"`
	Latitude             interface{}        `json:"latitude"`
}

func (q *Queries) GetReportsByDepartmentAndStatus(ctx context.Context, arg GetReportsByDepartmentAndStatusParams) ([]GetReportsByDepartmentAndStatusRow, error) {
	rows, err := q.db.Query(ctx, getReportsByDepartmentAndStatus, arg.Column1, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsByDepartmentAndStatusRow
	for rows.Next() {
		var i GetReportsByDepartmentAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReporterUniversityID,
			&i.Status,
			&i.ImageUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByReporter = `-- name: GetReportsByReporter :many
SELECT r.id, r.reporter_id, u.university_id as reporter_university_id, r.status, r.image_url, r.metadata, r.created_at, ST_X(r.location_geom::geometry) as longitude, ST_Y(r.location_geom::geometry) as latitude
FROM reports r
JOIN users u ON r.reporter_id = u.id
WHERE r.reporter_id = $1
ORDER BY r.created_at DESC
`

type GetReportsByReporterRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ReporterID           pgtype.UUID        `json:"reporter_id"`
	ReporterUniversityID string             `json:"reporter_university_id"`
	Status               ReportStatus       `json:"status"`
	ImageUrl             pgtype.Text        `json:"image_url"`
	Metadata             string             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Longitude            interface{}        `json:"longitude"`
	Latitude             interface{}        `json:"latitude"`
}

func (q *Queries) GetReportsByReporter(ctx context.Context, reporterID pgtype.UUID) ([]GetReportsByReporterRow, error) {
	rows, err := q.db.Query(ctx, getReportsByReporter, reporterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsByReporterRow
	for rows.Next() {
		var i GetReportsByReporterRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReporterUniversityID,
			&i.Status,
			&i.ImageUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsWithinRadius = `-- name: GetReportsWithinRadius :many
SELECT r.id, r.reporter_id, u.university_id as reporter_university_id, r.status, r.image_url, r.metadata, r.created_at, ST_X(r.location_geom::geometry) as longitude, ST_Y(r.location_geom::geometry) as latitude 
FROM reports r
JOIN users u ON r.reporter_id = u.id
WHERE ST_DWithin(r.location_geom::geography, ST_SetSRID(ST_MakePoint($1, $2), 4326)::geography, $3)
ORDER BY r.created_at DESC
`

type GetReportsWithinRadiusParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	StDwithin     interface{} `json:"st_dwithin"`
}

type GetReportsWithinRadiusRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ReporterID           pgtype.UUID        `json:"reporter_id"`
	ReporterUniversityID string             `json:"reporter_university_id"`
	Status               ReportStatus       `json:"status"`
	ImageUrl             pgtype.Text        `json:"image_url"`
	Metadata             string             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Longitude            interface{}        `json:"longitude"`
	Latitude             interface{}        `json:"latitude"`
}

func (q *Queries) GetReportsWithinRadius(ctx context.Context, arg GetReportsWithinRadiusParams) ([]GetReportsWithinRadiusRow, error) {
	rows, err := q.db.Query(ctx, getReportsWithinRadius, arg.StMakepoint, arg.StMakepoint_2, arg.StDwithin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsWithinRadiusRow
	for rows.Next() {
		var i GetReportsWithinRadiusRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReporterUniversityID,
			&i.Status,
			&i.ImageUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, university_id, pin_hash, auth_provider, provider_id, role, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.PinHash,
		&i.AuthProvider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUniversityID = `-- name: GetUserByUniversityID :one
SELECT id, university_id, pin_hash, auth_provider, provider_id, role, created_at FROM users WHERE university_id = $1
`

func (q *Queries) GetUserByUniversityID(ctx context.Context, universityID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUniversityID, universityID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.PinHash,
		&i.AuthProvider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateReportMetadata = `-- name: UpdateReportMetadata :exec
UPDATE reports SET metadata = $2 WHERE id = $1
`

type UpdateReportMetadataParams struct {
	ID       pgtype.UUID `json:"id"`
	Metadata string      `json:"metadata"`
}

func (q *Queries) UpdateReportMetadata(ctx context.Context, arg UpdateReportMetadataParams) error {
	_, err := q.db.Exec(ctx, updateReportMetadata, arg.ID, arg.Metadata)
	return err
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE reports SET status = $2, resolved_at = CASE WHEN $2::text = 'RESOLVED' THEN NOW() ELSE resolved_at END WHERE id = $1
`

type UpdateReportStatusParams struct {
	ID     pgtype.UUID  `json:"id"`
	Status ReportStatus `json:"status"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.Exec(ctx, updateReportStatus, arg.ID, arg.Status)
	return err
}
